name       : orbit2
version    : 2.14.19
release    : 4
source     :
    - https://download.gnome.org/sources/ORBit2/2.14/ORBit2-2.14.19.tar.bz2 : 55c900a905482992730f575f3eef34d50bda717c197c97c08fa5a6eafd857550
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : ORBit2 is a CORBA 2.4-compliant Object Request Broker
description: |
    ORBit2 is a CORBA 2.4-compliant Object Request Broker
builddeps  :
    - pkgconfig(libIDL-2.0)
    - gtk-doc
setup      : |
    %patch -Np1 -i $pkgfiles/build-fixes.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
